# Generated by Django 5.1.3 on 2025-06-14 03:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad_habitantes', models.IntegerField(null=True)),
                ('tasa_de_vulnerabilidad', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_de_fundacion', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
    ]
